export const SEARCH_PODCAST_REQUEST_STARTED = "SEARCH_PODCAST_REQUEST_STARTED";
export const SEARCH_PODCAST_SUCCESS = "SEARCH_PODCAST_SUCCESS";
export const SEARCH_PODCAST_FAILED = "SEARCH_PODCAST_FAILED";
export const SEARCH_URL_CHANGE = "SEARCH_URL_CHANGE";
export const TOGGLE_SHOW_MORE_INFO = "TOGGLE_SHOW_MORE_INFO";